### ISSUE TITLE
Create a generic plot() function for a census class tibble

### ISSUE THREAD

**Issue by pressleydavid** [ethanmarburger/St558_Project_1#7]
library(ggplot2) # put this in your setup code chunk
ggplot(_your_census_tibble_or_modification_,
aes(x = get(cat_var), y = get(num_var), weight = PWGTP)) +
geom_boxplot()

**Comment by ethanmarburger** [comment]
Added the code to our setup code chunk, don't know if it's right though

**Comment by pressleydavid** [comment]
fixed
